language: ruby
rvm:
  - 1.9.3
env:
  global:
    - secure: "YLsz6YhlbxXiaYzWv3Nfzonv6GW6rflhnZwxPmvqLCai2j2sqjtsQsEu+Sws/aPY4nS7Epyi9LXm4YHzpomvRixLMJpXWk1+6uqbMCR6gTqCdDWnzv2grDJb+8GntduDmuTJZkH1F3M3cE8GSYx9bLRlp0w0BDs08qqX6NXU0dw="
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system 1.8.25
  - gem --version
  - gem install -v 1.3.5 bundler
after_success:
  - bundle exec rake deploy
branches:
  except:
    - gh-pages
