language: ruby
rvm:
  - 1.9.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system 1.8.25
  - gem --version
  - gem install -v 1.3.5 bundler
branches:
  except:
    - gh-pages
