[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src https:; script-src https: data: 'unsafe-inline'; object-src 'none'; style-src 'self' 'unsafe-inline' https:; img-src data: 'self' https://referrer.disqus.com https://*.disquscdn.com https://dl.acm.org https://www.google-analytics.com https://*.twimg.com; media-src 'none'; child-src https://disqus.com; font-src https:; connect-src https:; report-uri https://mior.report-uri.io/r/default/csp/enforce"
  Referrer-Policy = "no-referrer-when-downgrade"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-UA-Compatible = "IE=Edge,chrome=1"
  X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/fonts/*.woff2"
  [headers.values]
  Content-Type = "application/font-woff2"

[[headers]]
  for = "/styles/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/fonts/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000"