
[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src https:; script-src https: data: 'unsafe-inline' 'unsafe-eval'; object-src 'none'; style-src 'self' 'unsafe-inline' https:; img-src data: 'self' https://referrer.disqus.com https://*.disquscdn.com https://dl.acm.org https://www.google-analytics.com https://*.twimg.com; media-src 'none'; frame-src https://disqus.com; font-src https: data:; connect-src https:; report-uri https://mior.report-uri.io/r/default/csp/enforce"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-UA-Compatible = "IE=Edge,chrome=1"
    X-XSS-Protection = "1; mode=block"
    Report-To = "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://mior.report-uri.com/a/d/g\"}],\"include_subdomains\":true}"
    NEL = "{\"report_to\":\"default\",\"max_age\":31536000,\"include_subdomains\":true}"
    Permissions-Policy = "interest-cohort=()"

[[headers]]
  for = "/fonts/*.woff2"

  [headers.values]
    Content-Type = "application/font-woff2"

[[headers]]
  for = "/styles/*"

  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/fonts/*"

  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/home.html"
  to = "/"

[[redirects]]
  from = "/2010/10/12/blog/dbus-screensaver-lock.html"
  to = "/blog/dbus-screensaver-lock/"

[[redirects]]
  from = "/2010/10/12/dbus-screensaver-lock/"
  to = "/blog/dbus-screensaver-lock/"

[[redirects]]
  from = "/2010/10/24/tweets-of-the-week/"
  to = "/blog/tweets-of-the-week/"

[[redirects]]
  from = "/2010/10/31/blog/dangers-of-strlen.html"
  to = "/blog/dangers-of-strlen/"

[[redirects]]
  from = "/2010/10/31/dangers-of-strlen/"
  to = "/blog/dangers-of-strlen/"

[[redirects]]
  from = "/2010/12/02/blog/designing-an-offline-cms.html"
  to = "/blog/designing-an-offline-cms/"

[[redirects]]
  from = "/2010/12/02/designing-an-offline-cms/"
  to = "/blog/designing-an-offline-cms/"

[[redirects]]
  from = "/2011/01/05/blog/rubbos.html"
  to = "/blog/rubbos/"

[[redirects]]
  from = "/2011/01/05/rubbos/"
  to = "/blog/rubbos/"

[[redirects]]
  from = "/2011/03/06/coloured-ssh-terminals/"
  to = "/blog/coloured-ssh-terminals/"

[[redirects]]
  from = "/2012/01/06/mysql-client-configuration/"
  to = "/blog/mysql-client-configuration/"

[[redirects]]
  from = "/2012/01/14/blog/unit-testing-django-model-mixins.html"
  to = "/blog/unit-testing-django-model-mixins/"

[[redirects]]
  from = "/2012/01/14/unit-testing-django-model-mixins/"
  to = "/blog/unit-testing-django-model-mixins/"

[[redirects]]
  from = "/2012/09/15/blog/node-js-skeleton-project.html"
  to = "/blog/node-js-skeleton-project/"

[[redirects]]
  from = "/2012/09/15/node-js-skeleton-project/"
  to = "/blog/node-js-skeleton-project/"

[[redirects]]
  from = "/2014/08/21/blog/cassandra-benchmarking.html"
  to = "/blog/cassandra-benchmarking/"

[[redirects]]
  from = "/2015/09/24/blog/automated-testing-of-dotfiles.html"
  to = "/blog/automated-testing-of-dotfiles/"

[[redirects]]
  from = "/blog/archive/2012.html"
  to = "/blog/"

[[redirects]]
  from = "/blog/archive/2015.html"
  to = "/blog/"
